In [212]:
import numpy as np
import pandas as pd

# Operation in NumPy

In [213]:
#making a array
i = np.array([1,2,3,4,5,6,7,8])
print(i)

[1 2 3 4 5 6 7 8]


In [214]:
#print the shape of the array,how many row and column in the array
print(i.shape)

(8,)


In [215]:
#change the shape and dimension and shape of the array
print(i.reshape(2,2,2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [216]:
x= np.array(['aman','atul','anju','abhinav'])
y= [True,True,True,False]
z= x[y]
print(z)
print(x[::-1])

['aman' 'atul' 'anju']
['abhinav' 'anju' 'atul' 'aman']


In [217]:
print(i[2]+i[4])    #addition
print(i[2]-i[4])    #subtraction
print(i[2]*i[4])    #multiplication
print(i[2]/i[4])    #division
print(i[2]%i[4])    #modulus
print(i[2]//i[4])   #floor division
print(i[2]**i[4])   #exponentiation

8
-2
15
0.6
3
0
243


In [218]:
print(i[2])

3


In [219]:
np.savetxt('library1.csv',i)#save a file in csv form
arr12=np.loadtxt('library1.csv')#load a file back from csv form
print(arr12)

[1. 2. 3. 4. 5. 6. 7. 8.]


In [220]:
np.save('library1.npy',i)#save a file in binary form
arr12=np.load('library1.npy') #load a file back from binary form
print(arr12)

[1 2 3 4 5 6 7 8]


In [221]:
print(np.sum(i))

36


In [222]:
print(np.mean(i))

4.5


In [223]:
print(np.median(i))

4.5


In [224]:
s=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
t = s.reshape(4,2,2)
print(t)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [225]:
#ndim function is use for finding the dimension of the function
#dtype function is used for findinf data type of the function
print(i.ndim)
print(i.dtype)
print(type(i))

1
int32
<class 'numpy.ndarray'>


In [226]:
#copy function is used for getting copy of the array and if we do any changes in the copy it do not effect orignal one
j=i.copy()
j[2]=16
print(j)


[ 1  2 16  4  5  6  7  8]


In [227]:
print(i)

[1 2 3 4 5 6 7 8]


In [228]:
#is help to sort the array
print(np.sort(i))

[1 2 3 4 5 6 7 8]


In [229]:
print(np.sort(x))

['abhinav' 'aman' 'anju' 'atul']


In [230]:
from numpy import random
#suffle use to suffle the the element in orignal array
#permutation is also used to suffle the element but permutation makes the copy of the array and shuffle it
print(np.random.shuffle(i))
print(np.random.permutation(i))


None
[8 5 2 1 3 6 4 7]


In [231]:
from numpy import linalg
r = np.array([3,42,445,2,5,7,46,2])
print(np.dot(i,r))#.dot is used to find the dot product between the array
print(np.matmul(i,j))#matmull is also used for multiplication between matrix but it is not flexible like .dot becaude it follow mathematical rule.
print(np.linalg.det(t))#.det is used to find the determinant of the matrix
print(np.linalg.inv(t))#.inv is used to find the inverse of the matrix
print(np.linalg.matrix_rank(t))#.matrix_rank is used to find the rank of the matrix

2180
200
[-2. -2. -2. -2.]
[[[-2.   1. ]
  [ 1.5 -0.5]]

 [[-4.   3. ]
  [ 3.5 -2.5]]

 [[-6.   5. ]
  [ 5.5 -4.5]]

 [[-8.   7. ]
  [ 7.5 -6.5]]]
[2 2 2 2]


In [232]:
np.random.seed(1)#is used to not change the array which is given to random function
print(np.random.rand(3,3))#is used to give the number in the whole number scale
print(np.random.randint(1,10,(3,3)))#is used to give umber in a prper range
print(np.random.choice(['a','t','r','t','s',2,4,5],5))#is used to choose randomely elemnt is array ehich is given
print(np.random.choice(['a','t','r','t','s',2,4,5],size =(3,3)))#is used to make a matrix from the given array in randomely choose the element

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
[[3 5 6]
 [3 5 3]
 [5 8 8]]
['t' 't' '5' '4' 'a']
[['4' '2' 't']
 ['t' '5' '5']
 ['2' '4' 't']]


# operation in pandas

In [233]:
data= {"name" :['farman','furkan','afsar','irshad'],
       "age" : [18,19,20,21],
       "city" : ['patna','bilaspur','raipur','delhi']}
g=pd.DataFrame(data)
print(g)


     name  age      city
0  farman   18     patna
1  furkan   19  bilaspur
2   afsar   20    raipur
3  irshad   21     delhi


In [234]:
#print first two row of the data set
print(g.head(2))

     name  age      city
0  farman   18     patna
1  furkan   19  bilaspur


In [235]:
#print last two row of data set
print(g.tail(2))

     name  age    city
2   afsar   20  raipur
3  irshad   21   delhi


In [236]:
#give the general information about the dataset
print(g.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    4 non-null      object
 1   age     4 non-null      int64 
 2   city    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes
None


In [237]:
#give the answer of statical operation perform in the dataset
print(g.describe())

             age
count   4.000000
mean   19.500000
std     1.290994
min    18.000000
25%    18.750000
50%    19.500000
75%    20.250000
max    21.000000


In [238]:
#give the indexing in the dataset
g=pd.DataFrame(data , index = ['a','b','c','d'])
print(g)

     name  age      city
a  farman   18     patna
b  furkan   19  bilaspur
c   afsar   20    raipur
d  irshad   21     delhi


In [239]:
#give the values of specific row in the dataset
print(g.loc['d'])

name    irshad
age         21
city     delhi
Name: d, dtype: object


In [240]:
#give the value of specific column in specific data set
print(g.iloc[2,1])

20


In [241]:
#sort the value with respect to given condition in bolean form
print(g['age']<19)

a     True
b    False
c    False
d    False
Name: age, dtype: bool


In [242]:
#sort the value with respect to given condition
print(g[g['age']<19])

     name  age   city
a  farman   18  patna


In [243]:
#save the file in csv format
g.to_csv('output.csv', index=False)

In [250]:
#save the file in excel format
g.to_excel('output.xlsx', index=False)

In [245]:
#find if there any null value in the dataset
g.isnull().sum()

name    0
age     0
city    0
dtype: int64

In [246]:
#fill the temparory value in the space of null value
g.fillna(0)

name  age      city
a  farman   18     patna
b  furkan   19  bilaspur
c   afsar   20    raipur
d  irshad   21     delhi

In [247]:
#drop the null value from the dataset
g.dropna()

name  age      city
a  farman   18     patna
b  furkan   19  bilaspur
c   afsar   20    raipur
d  irshad   21     delhi

In [248]:
#find the duplicated vaue in the dataset
g.duplicated().sum()

0

In [249]:
#drop the duplicated value from the dataset
g.drop_duplicates()

name  age      city
a  farman   18     patna
b  furkan   19  bilaspur
c   afsar   20    raipur
d  irshad   21     delhi